#!/usr/bin/env bash
#Confihgur web2 to match m own srver

sudo apt-get -y update
sudo apt-get -y install nginx

#firewall
sudo ufw allow 'Nginx HTTP'

sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/lilwildkid permanent;" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
n="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$n/" /etc/nginx/sites-enabled/default

m="server_name_;\n\tadd-header X-Served-By \$HOSTNAME;\n\trewrite ^\/redirect_me https:\/\/www.twitter.com\/lilwildkid permanent;"
sudo sed -i "s/server_name _;/$m/" /etc/nginx/sites-available/default

sudo service nginx restart
