#!/usr/bin/env bash
#install HAproxy on lb-01 server
# configure lb-001 server

sudo apt-get -y update
sudo apt-get -y install haproxy

#config file
server_config=\
"
frontend mumbua-frontend
	bind *:80
	mode http
	default_backend mumbua-backend
backend mumbua-backend
	balance roundrobin
	server 108643-web-01 54.236.188.125 check
	server 108643-web-02 54.144.158.189 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

#enable init sscript
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

#restart the service
sudo service haproxy restart
