#!/usr/bin/env bash
#this script displays "Best  school" ten times and Hi after the 9th iteration
j=0
while [ $j -le 9 ]
	do echo "Best School"
	((j++))
	if [[ $j -eq 9 ]]; then
		echo "Hi"
	fi
done

