#!/usr/bin/env bash
#this script displays numbers  1 to 20 , dispal 4, 9, 17 then bad luck from china, Japan and Italy
j=1
while [ $j -le 20 ]; do
	echo $j
	case $j in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	((j++))
done

