#!/usr/bin/env bash
# Use sed to change localhost IP and facebook.com IP
cp /etc/hosts ~/hosts.new
sed -i -e 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

